#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Handle game restart.
 */
void PrepareGameRestart(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
