#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Convert RGB565 value to RGB32.
 */
uint32_t rgb565_to_rgb32(uint16_t rgb565);

/**
 * Convert RGB32 value to RGB32.
 */
uint16_t rgb32_to_rgb565(uint32_t rgb565);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
