#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Store screenshot as PNG.
 * data is a pointer to screen data - 640x480x2 bytes, 2 bytes per pixel.
 * The pixel format is RGB565.
 */
bool StoreScreenshot(const uint16_t *data);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
