#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Write message into the debug log.
 * The string must be utf-8 encoded.
 */
bool DebugLogWrite(const char *message);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
