#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

struct ParsedCommandLine {
  bool editor_auto;
  bool editor;
  bool no_sound;
  bool quick_save;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Parse command line of the application.
 */
struct ParsedCommandLine ParseCommandLine(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
