#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Militia force in a sector.
 */
struct MilitiaCount {
  uint8_t green;
  uint8_t regular;
  uint8_t elite;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return militia force in a sector.
 */
struct MilitiaCount GetMilitiaInSector(uint8_t x, uint8_t y);

/**
 * Set militia force in a sector.
 */
void SetMilitiaInSector(uint8_t x, uint8_t y, struct MilitiaCount value);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
