#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * First part of STCI image header
 */
struct STCIHeaderHead {
  uint8_t ID[STCI_ID_LEN];
  uint32_t OriginalSize;
  uint32_t StoredSize;
  uint32_t TransparentValue;
  uint32_t Flags;
  uint16_t Height;
  uint16_t Width;
};

/**
 * Middle part of STCI image header describing RGB image
 */
struct STCIHeaderMiddleRGB {
  uint32_t uiRedMask;
  uint32_t uiGreenMask;
  uint32_t uiBlueMask;
  uint32_t uiAlphaMask;
  uint8_t ubRedDepth;
  uint8_t ubGreenDepth;
  uint8_t ubBlueDepth;
  uint8_t ubAlphaDepth;
};

/**
 * Middle part of STCI image header describing RGB image
 */
struct STCIHeaderMiddleIndexed {
  uint32_t uiNumberOfColours;
  uint16_t usNumberOfSubImages;
  uint8_t ubRedDepth;
  uint8_t ubGreenDepth;
  uint8_t ubBlueDepth;
  uint8_t cIndexedUnused[11];
};

/**
 * Middle part of STCI image header
 */
enum STCIHeaderMiddle_Tag {
  Rgb,
  Indexed,
};

struct STCIHeaderMiddle {
  enum STCIHeaderMiddle_Tag tag;
  union {
    struct {
      struct STCIHeaderMiddleRGB rgb;
    };
    struct {
      struct STCIHeaderMiddleIndexed indexed;
    };
  };
};

/**
 * Last part of STCI image header
 */
struct STCIHeaderEnd {
  uint8_t Depth;
  uint8_t unused1;
  uint8_t unused2;
  uint8_t unused3;
  uint32_t AppDataSize;
  uint8_t Unused[12];
};

/**
 * Last part of STCI image header
 */
struct STCIHeaderTmp {
  struct STCIHeaderHead head;
  struct STCIHeaderMiddle middle;
  struct STCIHeaderEnd end;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

bool ReadSTCIHeader(FileID file_id, struct STCIHeaderTmp *data);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
