#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define STCI_ID_LEN 4

/**
 * First part of STCI image header
 */
struct STCIHeaderHead {
  uint8_t ID[STCI_ID_LEN];
  uint32_t OriginalSize;
  uint32_t StoredSize;
  uint32_t TransparentValue;
  uint32_t Flags;
  uint16_t Height;
  uint16_t Width;
};

/**
 * Last part of STCI image header
 */
struct STCIHeaderEnd {
  uint8_t Depth;
  uint32_t AppDataSize;
  uint8_t Unused[12];
};

/**
 * Last part of STCI image header
 */
struct STCIHeaderTmp {
  struct STCIHeaderHead head;
  struct STCIHeaderEnd end;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

bool ReadSTCIHeader(FileID file_id, struct STCIHeaderTmp *data);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
