#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

struct SamSiteLocation {
  uint8_t x;
  uint8_t y;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern const struct SamSiteLocation SamSiteLocations[4];

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
