#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Change the current working directory.
 * The path string must be utf8 encoded.
 */
bool Plat_SetCurrentDirectory(const char *path_utf8);

/**
 * Check if directory exists.
 */
bool Plat_DirectoryExists(const char *path_utf8);

/**
 * Check if file or directory exists.
 */
bool Plat_FileEntityExists(const char *path_utf8);

/**
 * Create directory.
 */
bool Plat_CreateDirectory(const char *path_utf8);

bool Plat_DeleteFile(const char *path_utf8);

/**
 * Remove all files in a directory, but not the directory itself or any subdirectories.
 */
bool Plat_RemoveFilesInDirectory(const char *path_utf8);

/**
 * Remove the directory and all its content including subdirectories.
 */
bool Plat_RemoveDirectory(const char *path_utf8);

/**
 * Remove read-only attribute from a file.
 */
bool Plat_RemoveReadOnlyAttribute(const char *path_utf8);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
