#ifndef __RUST_BINDINGS_H
#define __RUST_BINDINGS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define MAP_WORLD_X 18

#define MAP_WORLD_Y 18

/**
 * Sector ID 0-255 (16x16)
 */
typedef uint8_t SectorID8;

/**
 * Sector ID 0-324 (18x18)
 */
typedef int16_t SectorID16;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Convert coordinates ([1-16], [1-16]) to 0-255 index.
 * This function should be prefered over GetSectorID8_STATIC macro.
 */
SectorID8 GetSectorID8(uint8_t x, uint8_t y);

/**
 * Get X [1-16] from SectorID8
 */
uint8_t SectorID8_X(SectorID8 sector_id);

/**
 * Get Y [1-16] from SectorID8
 */
uint8_t SectorID8_Y(SectorID8 sector_id);

/**
 * Convert coordinates (1-16, 1-16) to 0-324 index.
 */
SectorID16 GetSectorID16(uint8_t x, uint8_t y);

/**
 * Get X [1-16] from SectorID16
 */
uint8_t SectorID16_X(SectorID16 sector_id);

/**
 * Get Y [1-16] from SectorID16
 */
uint8_t SectorID16_Y(SectorID16 sector_id);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* __RUST_BINDINGS_H */
