#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define SAM_1_X 2

#define SAM_2_X 15

#define SAM_3_X 8

#define SAM_4_X 4

#define SAM_1_Y 4

#define SAM_2_Y 4

#define SAM_3_Y 9

#define SAM_4_Y 14
